version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.40.0
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.1.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
  - dependency-name: karma-rollup-preprocessor
    versions:
    - 7.0.6
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.1.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: jasmine
    versions:
    - 3.6.4
